#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/xleo/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# Background
#fbsetroot -mod 33 33 -bg black -fg grey6
#fbsetroot -gradient Vertical -from SlateGrey -to SlatBlue
fbsetbg -c /home/xleo/Pictures/Wallpapers/blueprint_1920x1080.jpg

# Screensaver
xscreensaver -no-splash &

dropbox start &
nm-applet &
xfce4-power-manager --no-daemon 2>&1 > /dev/null &
#xcompmgr &
pad off
syndaemon -i 2 -K d & #disable touchpad while typing
#syndaemon -i 2 -K -t -R -d
#pcmanfm --desktop &
setxkbmap -option "caps:swapescape"

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/xleo/.fluxbox/log"
